apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app:  myapp-service
spec:
  selector:
    app: myjavawebapp
  type: NodePort
  ports:
    - nodePort: 25000
      port: 81
      targetPort: 81
